version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/ingest"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/services/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/services/ingest"
    schedule:
      interval: "weekly"
