version: '3.9'
services:
  api:
    build: ./services/api
    env_file:
      - .env.example
    ports:
      - "8080:8080"
    depends_on:
      - opensearch
      - postgres
  ingest:
    build: ./services/ingest
    env_file:
      - .env.example
    depends_on:
      - opensearch
      - postgres
      - redis
  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
  postgres:
    image: postgres:16
    env_file:
      - .env.example
    volumes:
      - ./db/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
