version: '3.9'
services:
  api:
    build: ./services/api
    ports:
      - "8080:8080"
    environment:
      - OPENSEARCH_URL=${OPENSEARCH_URL:-http://opensearch:9200}
    depends_on:
      - opensearch
  placeholder:
    image: alpine
  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
