[build-system]
requires = ["setuptools>=78.1.1"]
build-backend = "setuptools.build_meta"

[project]
name = "nzbidx-ingest"
version = "0.0.0"
dependencies = [
    "python-dotenv",
    "opensearch-py",
    "psycopg[binary]>=3.1",
    "setuptools>=78.1.1",
]
