[build-system]
requires = ["setuptools>=78.1.1"]
build-backend = "setuptools.build_meta"

[project]
name = "nzbidx-api"
version = "0.0.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "orjson",
    "opensearch-py",
    "httpx",
    "sqlalchemy>=2",
    "asyncpg",
    "redis",
]

