name: Security Audit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  PIP_AUDIT_LEVEL: ${{ vars.PIP_AUDIT_LEVEL || 'high' }}
  PYTHONPATH: .

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, ingest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -e services/${{ matrix.service }}
      - run: pip install pip-audit
      - run: pip-audit --fail-on ${{ env.PIP_AUDIT_LEVEL }}
  sbom:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, ingest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -e services/${{ matrix.service }}
      - run: pip install cyclonedx-bom
      - run: cyclonedx-bom -e -o sbom-${{ matrix.service }}.json
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.service }}
          path: sbom-${{ matrix.service }}.json
