name: Security Audit

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONPATH: .

jobs:
  pip-audit:
    runs-on: self-hosted
    strategy:
      matrix:
        service: [api, ingest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e services/${{ matrix.service }}
      - run: pip install "pip-audit>=2.9.0"
      - run: pip-audit --skip-editable

  sbom:
    runs-on: self-hosted
    strategy:
      matrix:
        service: [api, ingest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e services/${{ matrix.service }}
      - run: pip install cyclonedx-bom
      - run: cyclonedx-py environment -o sbom-${{ matrix.service }}.json
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.service }}
          path: sbom-${{ matrix.service }}.json
