name: Auto Merge

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted
    steps:
      - name: Setup GH CLI
        run: |
          sudo rm -f /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Merge pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
          REPO: ${{ github.repository }}
        run: |
          pr="${PR_NUMBER}"
          if [ -z "$pr" ]; then
            pr=$(gh pr list --head "$HEAD_BRANCH" --json number -q '.[0].number' --repo "$REPO")
          fi
          gh pr merge "$pr" --merge --delete-branch --repo "$REPO"
