name: pre-commit

on:
  pull_request:

permissions:
  contents: write

jobs:
  pre-commit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }} --depth=1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: .github/workflows/requirements/pre-commit.txt
      - run: pip install -r .github/workflows/requirements/pre-commit.txt
      - uses: pre-commit/action@v3.0.1
        continue-on-error: true
        with:
          extra_args: "--files $(git diff --name-only origin/${{ github.base_ref }}...HEAD | tr '\n' ' ')"
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: apply pre-commit fixes"
          branch: ${{ github.head_ref }}
